FROM maven:3.9-amazoncorretto-21 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar

# Environment variables that can be overridden
ENV SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/ecommerce_app
ENV SPRING_DATASOURCE_USERNAME=root
ENV SPRING_DATASOURCE_PASSWORD=2710
ENV JWT_SECRET=lYq3N8rZKe2Q7MNAV3LfK8m7UkSLgQg8waYaSeBLRzw

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
